# Generated by Django 3.1.4 on 2020-12-25 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('heading0', models.CharField(max_length=100)),
                ('heading1', models.CharField(max_length=100)),
                ('heading2', models.CharField(max_length=100)),
                ('published', models.DateTimeField()),
                ('thumbnail', models.ImageField(default='', upload_to='blog/images')),
            ],
        ),
    ]
