# Generated by Django 3.1.4 on 2020-12-25 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='content0',
            field=models.CharField(default='', max_length=1000000),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content1',
            field=models.CharField(default='', max_length=1000000),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content2',
            field=models.CharField(default='', max_length=1000000),
        ),
    ]
